CREATE DATABASE
IF NOT EXISTS shares DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user` (
  `SEQ_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `USER_ID` varchar(20) NOT NULL COMMENT '用户编号',
  `USERNAME` varchar(20) NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(50) NOT NULL COMMENT '密码',
  `MOBILE` varchar(11) DEFAULT NULL COMMENT '手机号',
  `ADDRESS` varchar(200) DEFAULT NULL COMMENT '地址',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态',
  `IS_DELETE` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N' COMMENT '数据状态 Y/N',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `COMMENTS` varchar(200) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`SEQ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sys_resource` (
  `SEQ_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `RES_CODE` varchar(80) COLLATE utf8_bin NOT NULL COMMENT '资源编码,唯一',
  `RES_NAME` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '资源名称',
  `PARENT_CODE` varchar(80) COLLATE utf8_bin DEFAULT NULL COMMENT '父编号、最上级的父编号为0',
  `RES_ICON` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '菜单图标,前端class名称',
  `RES_DESC` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '资源描述',
  `RES_TYPE` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '资源类型,MENU:页面菜单,BUTTON:操作(按钮),NODE:节点,类似于父节点没有页面',
  `SEQUENCE` int(11) DEFAULT NULL COMMENT '页面菜单目录,根据此字段排序',
  `CREATOR` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `UPDATER` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '修改人',
  `IS_DELETE` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N' COMMENT '数据状态 Y/N',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `COMMENTS` varchar(200) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='资源表 \r\nAMOUNT = 200\r\nSELECT = MEDIUM\r\nINSERT = VERY LOW\r\nUPDATE = VERY LOW';


CREATE TABLE `sys_role_resource` (
  `SEQ_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `ROLE_CODE` varchar(80) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `RES_CODE` varchar(80) COLLATE utf8_bin NOT NULL COMMENT '资源编码',
  `CREATOR` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `UPDATER` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '修改人',
  `IS_DELETE` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N' COMMENT '数据状态 Y/N',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `COMMENTS` varchar(200) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`SEQ_ID`),
  KEY `MIDX_TOP_ROLE_RESOURCE#ROLE_CODE#RES_CODE` (`ROLE_CODE`,`RES_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='资源角色关联表 \r\nAMOUNT = 100000\r\nSELECT = MEDIUM\r\nINSERT = VERY LOW\r\nUPDATE = VERY LOW';


CREATE TABLE `sys_user_role` (
  `SEQ_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `USER_ID` bigint(20) NOT NULL COMMENT '用户Id',
  `ROLE_CODE` varchar(80) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `CREATOR` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `UPDATER` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '修改人',
  `IS_DELETE` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N' COMMENT '数据状态 Y/N',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `COMMENTS` varchar(200) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户角色关联表 \r\nAMOUNT = 2000\r\nSELECT = MEDIUM\r\nINSERT = VERY LOW\r\nUPDATE = VERY LOW';