INSERT INTO `sys_role`(`ROLE_CODE`,`ROLE_NAME`,`ROLE_DESC`,`IS_DELETE`,`CREATOR`,`UPDATER`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('admin','超级管理员','超级管理员','N','SYSTEM',NULL,NOW(),NULL,NULL);
INSERT INTO `sys_role`(`ROLE_CODE`,`ROLE_NAME`,`ROLE_DESC`,`IS_DELETE`,`CREATOR`,`UPDATER`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('finance','财务专员','财务专员','N','SYSTEM',NULL,NOW(),NULL,NULL);
INSERT INTO `sys_role`(`ROLE_CODE`,`ROLE_NAME`,`ROLE_DESC`,`IS_DELETE`,`CREATOR`,`UPDATER`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('hr','人事专员','财务专员','N','SYSTEM',NULL,NOW(),NULL,NULL);
INSERT INTO `sys_role`(`ROLE_CODE`,`ROLE_NAME`,`ROLE_DESC`,`IS_DELETE`,`CREATOR`,`UPDATER`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('staff','行政专员','财务专员','N','SYSTEM',NULL,NOW(),NULL,NULL);


INSERT INTO `sys_user`(`USER_ID`,`USERNAME`,`PASSWORD`,`MOBILE`,`ADDRESS`,`STATUS`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('1','admin','21232f297a57a5a743894a0e4a801fc3',NULL,NULL,NULL,'N',NOW(),NULL,NULL);
INSERT INTO `sys_user`(`USER_ID`,`USERNAME`,`PASSWORD`,`MOBILE`,`ADDRESS`,`STATUS`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('2','13818889999','21232f297a57a5a743894a0e4a801fc3',NULL,NULL,NULL,'N',NOW(),NULL,NULL);


INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('home','主页','home','0','主页','M01','fa fa-home','MENU',1,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('system','系统管理',NULL,'0','系统管理','M02','fa fa-user','MENU',2,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('user:list','用户管理','user/list','system','用户管理','M0201','fa fa-user','MENU',3,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('user:add','新增用户','user/add','user:list','新增用户','M020101',NULL,'BUTTON',4,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('user:detail','用户详情','user/detail','user:list','用户详情','M020102',NULL,'BUTTON',5,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('user:update','用户信息修改','user/update','user:list','用户信息修改','M020103',NULL,'BUTTON',6,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('role:list','角色管理','role/list','system','角色管理','M0202','fa fa-user','MENU',7,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('role:add','新增角色','role/add','role:list','新增角色','M020201',NULL,'BUTTON',8,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);
INSERT INTO `sys_resource`(`RES_CODE`,`RES_NAME`,`RES_URL`,`PARENT_CODE`,`RES_DESC`,`MENU_CODE`,`RES_ICON`,`RES_TYPE`,`SEQUENCE`,`CREATOR`,`UPDATER`,`IS_DELETE`,`CREATE_TIME`,`UPDATE_TIME`,`COMMENTS`) VALUES ('role:detail','角色详情','role/detail','role:list','角色详情','M020202',NULL,'BUTTON',9,'SYSTEM','SYSTEM','N',NOW(),NULL,NULL);

INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','home','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','system','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','user:list','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','user:add','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','user:detail','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','user:update','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','role:list','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','role:add','N',NOW());
INSERT INTO `sys_role_resource`(ROLE_CODE,RES_CODE,IS_DELETE,CREATE_TIME) VALUES ('admin','role:detail','N',NOW());

INSERT INTO `sys_user_role` (USER_ID,ROLE_CODE,IS_DELETE,CREATE_TIME) VALUES ('1','admin','N',NOW());